version: 0.2

phases: 
    install:
        runtime-versions:
            python: 3.10
        commands:
            - pip install pytest
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - python -m pytest
    post_build:
        commands:
            - echo "we are in the post build phase"